#! /usr/bin/env python
import sys,os,subprocess
username = "mr-star-k"
password = "pramod%4012345"
os.system("git add .")
cmsg = input("enter commit message: ")
os.system("git commit -m \"%s\""%(cmsg))
reposit = os.popen("git remote get-url origin").read()[8:-1]
os.system("git push https://%s:%s@%s"%(username,password,reposit))
