#! /usr/bin/env python

password="Your Password"
import sys,os
if len(sys.argv)==1:
    os.system("echo \"Enter any package to install\"")
else:
    args = ""
    for i in range(1,len(sys.argv)):
        args+=sys.argv[i]+" "
    os.system("echo %s | sudo -S apt install %s"%(password,args))
